// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelInjection() {
  return window['go']['main']['App']['CancelInjection']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetMinecraftSkinBase64() {
  return window['go']['main']['App']['GetMinecraftSkinBase64']();
}

export function GetMinecraftUsername() {
  return window['go']['main']['App']['GetMinecraftUsername']();
}

export function GetMinecraftVersion() {
  return window['go']['main']['App']['GetMinecraftVersion']();
}

export function IsMinecraftRunning() {
  return window['go']['main']['App']['IsMinecraftRunning']();
}

export function KillMinecraft() {
  return window['go']['main']['App']['KillMinecraft']();
}

export function LaunchMinecraft() {
  return window['go']['main']['App']['LaunchMinecraft']();
}

export function LogJS(arg1, arg2) {
  return window['go']['main']['App']['LogJS'](arg1, arg2);
}

export function OpenConsole() {
  return window['go']['main']['App']['OpenConsole']();
}

export function PerformInjection(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['PerformInjection'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectDLL() {
  return window['go']['main']['App']['SelectDLL']();
}

export function SetRPCIngame() {
  return window['go']['main']['App']['SetRPCIngame']();
}

export function SetRPCLauncher() {
  return window['go']['main']['App']['SetRPCLauncher']();
}

export function StartUpdate(arg1, arg2) {
  return window['go']['main']['App']['StartUpdate'](arg1, arg2);
}

export function ValidateDLLPath(arg1) {
  return window['go']['main']['App']['ValidateDLLPath'](arg1);
}
